# Generated by Django 4.1.5 on 2023-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Имя отчета"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="user_created_email",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Email юриста"
            ),
        ),
    ]
