version: '3.8'
services:
  dontsueme:
    container_name: dontsueme
    image: kazhem/dontsueme:${DONTSUEME_IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data"
    environment:
      DB_DIR: "/data"
      YC_LOCKBOX_SECRET_ID: "e60000000000000000"
# by default should be claimed from meta
      YC_IAM_TOKEN_METADATA_URL: "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token"
      S3_REGION: "ru-central1"
      S3_ENDPOINT_URL: "https://storage.yandexcloud.net"
      S3_BUCKET_NAME: "yc-auth-test"
      S3_BUCKET_FOLDER: "reports"
