# Generated by Django 4.1.5 on 2023-02-09 14:06

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = []

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User
        superuser = User.objects.create_superuser(
            username=settings.DJANGO_SU_NAME,
            email=settings.DJANGO_SU_EMAIL,
            password=settings.DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
